[project]
name = "My Project"
version = "0.1.0"
# Project's code
location = "/Users/bbh/Projects/demo/blue/test"

[schema.default]
sql_dump = "/Users/bbh/Projects/demo/blue/test/default.sql"
hostname = "localhost"
database = "drupal_default"
username = "drupal_default"
password = "drupal_default"
[schema.foo]
sql_dump = "/Users/bbh/Projects/demo/blue/test/foo.sql"
hostname = "localhost"
database = "drupal_foo"
username = "drupal_foo"
password = "drupal_foo"
[schema.bar]
sql_dump = "/Users/bbh/Projects/demo/blue/test/bar.sql"
hostname = "localhost"
database = "drupal_bar"
username = "drupal_bar"
password = "drupal_bar"

[stack]
packages = [
  "bluespark/mysql",
  "bluespark/apache22",
  "bluespark/php7"
]

[services]
habitat_depot = ""
docker_registry = ""
nexus_repository = ""

[habitat]
location = "~/.bsp/bin/hab"
download_url = "https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux"
