# General
[project]
name = "myproject"
version = "0.1.0"
path = "~/Projects/demo/blue/project1" # Project's location

# Databases
[database.default]
sql_dump = "default.sql" # It's based on location
hostname = "localhost"
database = "drupal_default"
username = "drupal_default"
password = "drupal_default"
# [database.foo]
# sql_dump = "/Users/bbh/Projects/demo/blue/test/foo.sql"
# hostname = "localhost"
# database = "drupal_foo"
# username = "drupal_foo"
# password = "drupal_foo"
# [database.bar]
# sql_dump = "/Users/bbh/Projects/demo/blue/test/bar.sql"
# hostname = "localhost"
# database = "drupal_bar"
# username = "drupal_bar"
# password = "drupal_bar"

[docker]
image_tag = "myproject:latest"
image_base = "bluespark:base_centos7-hab0.24.1"
registry = "147905667315.dkr.ecr.us-west-1.amazonaws.com/"

[nexus]
repository = ""

[habitat]
packages = [
  "bluespark/mysql",
  "bluespark/httpd",
  "bluespark/php7"
]
depot = ""
bsp_path = ".bsp"
download_url_macos = "https://api.bintray.com/content/habitat/stable/darwin/x86_64/hab-%24latest-x86_64-darwin.zip?bt_package=hab-x86_64-darwin"
download_url_linux = "https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux"
